// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: message/login.proto

package login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//0x100
type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//用户id
	UserID int32 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	//平台id
	AppID int32 `protobuf:"varint,2,opt,name=appID,proto3" json:"appID,omitempty"`
	//平台账号
	OpenID string `protobuf:"bytes,3,opt,name=openID,proto3" json:"openID,omitempty"`
	//密码
	Pwd string `protobuf:"bytes,4,opt,name=pwd,proto3" json:"pwd,omitempty"`
	//设备id
	DevID string `protobuf:"bytes,5,opt,name=devID,proto3" json:"devID,omitempty"`
	//设备名称
	DevName string `protobuf:"bytes,6,opt,name=devName,proto3" json:"devName,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_message_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *LoginReq) GetAppID() int32 {
	if x != nil {
		return x.AppID
	}
	return 0
}

func (x *LoginReq) GetOpenID() string {
	if x != nil {
		return x.OpenID
	}
	return ""
}

func (x *LoginReq) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *LoginReq) GetDevID() string {
	if x != nil {
		return x.DevID
	}
	return ""
}

func (x *LoginReq) GetDevName() string {
	if x != nil {
		return x.DevName
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//登陆用户
	UserID int32 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	//是否连接
	Reconnected bool `protobuf:"varint,3,opt,name=reconnected,proto3" json:"reconnected,omitempty"`
	//连接服务器
	ServerID int32 `protobuf:"varint,4,opt,name=serverID,proto3" json:"serverID,omitempty"`
	//连接房间/地图
	RoomID int32 `protobuf:"varint,5,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_message_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *LoginResp) GetReconnected() bool {
	if x != nil {
		return x.Reconnected
	}
	return false
}

func (x *LoginResp) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *LoginResp) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

var File_message_login_proto protoreflect.FileDescriptor

var file_message_login_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65,
	0x76, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x76, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x64, 0x65, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x79, 0x0a, 0x09, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_login_proto_rawDescOnce sync.Once
	file_message_login_proto_rawDescData = file_message_login_proto_rawDesc
)

func file_message_login_proto_rawDescGZIP() []byte {
	file_message_login_proto_rawDescOnce.Do(func() {
		file_message_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_login_proto_rawDescData)
	})
	return file_message_login_proto_rawDescData
}

var file_message_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_login_proto_goTypes = []interface{}{
	(*LoginReq)(nil),  // 0: LoginReq
	(*LoginResp)(nil), // 1: LoginResp
}
var file_message_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_login_proto_init() }
func file_message_login_proto_init() {
	if File_message_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_login_proto_goTypes,
		DependencyIndexes: file_message_login_proto_depIdxs,
		MessageInfos:      file_message_login_proto_msgTypes,
	}.Build()
	File_message_login_proto = out.File
	file_message_login_proto_rawDesc = nil
	file_message_login_proto_goTypes = nil
	file_message_login_proto_depIdxs = nil
}
